theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
github:
  is_project_page: false
author: Hovnatan Karapetyan
