title: Public repositories for annotate.online and superannotate.ai
author:
  name: Hovnatan Karapetyan
  email: hovnatan@superannotate.com
description: > # this means to ignore newlines until "show_excerpts:"
  Public open source components' repositories for annotate.online and superannotate.ai.

theme: minima
minima:
  skin: sunrise
plugins:
  - jekyll-seo-tag
  - jekyll-feed
